[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
nixPkgs = ["nodejs"]

[nixpacks.phases.setup]
nixPkgs = ["nodejs", "npm"]

[nixpacks.phases.install]
cmds = ["cd backend && npm ci"]

[nixpacks.phases.build] 
cmds = ["echo 'Build phase completed'"]

[nixpacks.phases.start]
cmd = "cd backend && npm start"